package com.smart.rh.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents alerts generated by the system (e.g., device offline, high error rate).
 */
@Entity
@Table(
    name = "alert",
    indexes = {
        @Index(name = "idx_alert_device", columnList = "device_id"),
        @Index(name = "idx_alert_created", columnList = "created_at DESC"),
        @Index(name = "idx_alert_status", columnList = "acknowledged")
    }
)
@Getter
@Setter
public class Alert extends BaseEntity {

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "device_id", nullable = false)
    private Device device;

    @NotBlank
    @Column(name = "alert_type", nullable = false, length = 50)
    private String alertType;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AlertSeverity severity;

    @NotBlank
    @Column(name = "message", columnDefinition = "VARCHAR(500)")
    private String message;

    @Column(nullable = false)
    private Boolean acknowledged = false;

    /**
     * Who acknowledged the alert (username or system)
     */
    @Column(name = "acknowledged_by", length = 255)
    private String acknowledgedBy;

    /**
     * Additional context stored as JSON
     */
    @Column(columnDefinition = "JSON")
    private String context;

    public enum AlertSeverity {
        INFO,
        WARNING,
        CRITICAL
    }
}
