package com.smart.rh.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;

/**
 * Records every clocking event generated by the Python AI recognition module
 * or the IoT MQTT listener. Real-time updates are pushed to Angular
 * via WebSocket topic /topic/attendance.
 */
@Entity
@Table(
    name = "attendance",
    indexes = {
        @Index(name = "idx_att_employe_ts", columnList = "employe_id, clocked_at"),
        @Index(name = "idx_att_ts",         columnList = "clocked_at")
    }
)
@Getter
@Setter
public class Attendance extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "employe_id", nullable = false)
    private Employe employe;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private AttendanceType type;

    @NotNull
    @Column(name = "clocked_at", nullable = false)
    private Instant clockedAt;

    /** AI recognition confidence score (0.0 – 1.0). */
    @Column
    private Double confidence;

    @Column(name = "camera_id", length = 100)
    private String cameraId;

    @Column(name = "site_id", length = 100)
    private String siteId;

    /** Optional path to the raw snapshot used for recognition. */
    @Column(name = "raw_image_path", length = 500)
    private String rawImagePath;
}
