# Mosquitto MQTT Broker — SMART RH 4.0
# MQTT listener
listener 1883
allow_anonymous true

# WebSocket listener (for browser clients)
listener 9001
protocol websockets
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
